package com.example.projetsy43.model.entities

//Datetime either store as Long either as String


/**
 * Represents an Event entity in the application.
 *
 * @param cid Unique ID generated by the database (Firebase key).
 * @param name Name of the event.
 * @param description Description of the event.
 * @param datetime Date and time of the event (consider formatting or using Long timestamp).
 * @param address Location of the event.
 * @param seller_id ID of the user who created the event.
 * @param type Type of event (e.g., Concert, Festival, etc.).
 * @param price Entry price for the event.
 * @param capacity Maximum number of attendees.
 * @param avaliablecapacity Number of remaining spots.
 * @param cover_image URL of the cover image.
 * @param attraction Comma-separated list of artists or performers. At least for now
 */
data class Event(
    var cid : String = "",
    val name : String = "",
    val description : String = "No description was added yet",
    val datetime: String = "", //Here might have to change the type
    val address: String = "",
    val seller_id : String = "",
    val type : String = "",
    val price: Double = 0.0,
    val capacity: Int = 0,
    val avaliablecapacity : Int = 0,
    val cover_image : String = "defaultroute", //Here add the default route!
    val attraction: String = "", //Find a way here to represent many artists: First idea, artists separated by coma
)
